services:
  generator-service:
    build:
      context: ./generator
    container_name: generator-service
    ports:
      - "8080:8080"

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  invoker-service:
    build:
      context: ./invoker
    container_name: invoker-service
    ports:
      - "8081:8081"
    depends_on:
      - generator-service
      - redis
    environment:
      - GENERATOR_SERVICE_URL=http://generate-service:8080/generate

volumes:
  redis_data:
